name: Build Windows

on:
  push:
    branches:
      - '*'

jobs:
    build_linux:
        name: Build
        runs-on: windows-latest

        steps:
          - uses: actions/checkout@v4
        
          - name: Install GNU make and gcc
            run: |
                choco install make
                choco install mingw

          - name: Build
            run: |
                powershell
                make build

          - name: Print Result
            run: ./build/main