name: Build Linux

on:
  push:
    branches:
      - '*'

jobs:
    build_linux:
        name: Build
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Build
            run: make build

          - name: Print Result
            run: ./build/main
